### PR TITLE
[breaking] Less strict in types which we accept and unified indices/coords behaviour.

### LINKED ISSUE #77: BBox is Float or Int
Currently, BBox is defined as Float64.

```julia
bbox::NamedTuple{(:min_x, :min_y, :max_x, :max_y),Tuple{Float64, Float64, Float64, Float64}})
```

This is mostly true, but BBox can also be Int64. Or a combination of them (each element can be either Int or Float). `GeoArrays` does not handle this.

```julia
julia> GeoArrays.bbox_to_affine((10,10), (min_x=10, min_y=10, max_x=100, max_y=100))
ERROR: MethodError: no method matching bbox_to_affine(::Tuple{Int64, Int64}, ::NamedTuple{(:min_x, :min_y, :max_x, :max_y), NTuple{4, Int64}})
Closest candidates are:
  bbox_to_affine(::Tuple{Integer, Integer}, ::NamedTuple{(:min_x, :min_y, :max_x, :max_y), NTuple{4, Float64}})
```

### PR DESCRIPTION
**Pull request by evetion**
Refactored `indices` and `coords` behaviour. Removed `centercoords` variants, replaced them with `strategy` argument in relevant methods.
Default behaviour is now to use `Center` everywhere.

Improved online documentation by docstrings and added README to it.

Fixes #77

### CODE REVIEW

File: src/geoarray.jl [hunk 1]
```diff
@@ -1,22 +1,95 @@
...
+    GeoArray{T <: Union{Real,Union{Missing,Real}}} <: AbstractArray{T,3}
+
+A GeoArray is an AbstractArray, an AffineMap for calculating coordinates based on the axes and a CRS definition to interpret these coordinates into in the real world.
+It's three dimensional and can be seen as a stack (3D) of 2D geospatial rasters (bands), the dimensions are :x, :y, and :bands.
+The AffineMap and CRS (coordinates) only operate on the :x and :y dimensions.
+"""
 mutable struct GeoArray{T <: Union{Real,Union{Missing,Real}}} <: AbstractArray{T,3}
     A::AbstractArray{T,3}
     f::AffineMap
     crs::WellKnownText{GeoFormatTypes.CRS,<:String}
```
Comment (visr) [inline src/geoarray.jl:11]: Hmm none of the three fields are concrete types, right? Is there a reason you went with that? Since normally it's best to avoid such that the compiler can specialize: https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type

Comment (evetion) [reply src/geoarray.jl:11]: A is either an ArchGDAL IDataSet or an Array{T}.
AffineMap just isn't concrete, it's subs (linear and translation can be any kind of array, often StaticArrays, but not always).
WellKnownText also isn't concrete.

I'm happy to take suggestions how to resolve this.
